quarkus:
  banner:
    enabled: false
  hibernate-orm:
    database:
      generation: none
  micrometer:
    binder:
      http-server:
        ignore-patterns:
          - '/q.*'

mp:
  openapi:
    extensions:
      smallrye:
        info:
          title: ksetl API
          version: 0.0.1
          description: API for ksetl
          contact:
            email: techsupport@ksetl.com
            name: ksetl API Support
            url: https://github.com/ksetl/ksetl-api
          license:
            name: Apache 2.0
            url: http://www.apache.org/licenses/LICENSE-2.0.html